Traceback (most recent call last):
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/nicola/.pyenv/versions/3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

fig1 = plt.figure()
ax1 = fig1.add_subplot(111, aspect='equal')
ax1.add_patch(
    patches.Rectangle((0, 0), width, height))
------------------

[0;31m------------------------------------------------------[0m
[0;31mNameError[0m            Traceback (most recent call last)
[0;32m<ipython-input-2-956bfa14e2e9>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0max1[0m [0;34m=[0m [0mfig1[0m[0;34m.[0m[0madd_subplot[0m[0;34m([0m[0;36m111[0m[0;34m,[0m [0maspect[0m[0;34m=[0m[0;34m'equal'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m ax1.add_patch(
[0;32m----> 4[0;31m     patches.Rectangle((0, 0), width, height))
[0m
[0;31mNameError[0m: name 'patches' is not defined
NameError: name 'patches' is not defined

